bball_draft_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/urls.py
from django.urls import path
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [

    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('players/', views.players_index, name='index'),
    path('players/<int:player_id>/', views.players_detail, name='detail'),
    path('players/create/', views.PlayerCreate.as_view(), name='players_create'),
    path('players/<int:pk>/update/', views.PlayerUpdate.as_view(), name='players_update'),
    path('players/<int:pk>/delete/', views.PlayerDelete.as_view(), name='players_delete'),
    path('players/<int:player_id>/add_game/', views.add_game, name='add_game'),
    path('players/<int:player_id>/assoc_shoe/<int:shoe_id>/', views.assoc_shoe, name='assoc_shoe'),
    path('players/<int:player_id>/assoc_shoe/<int:shoe_id>/delete/', views.assoc_shoe_delete, name='assoc_shoe_delete'),
    path('shoes/', views.ShoeList.as_view(), name='shoes_index'),
    path('shoes/<int:pk>/', views.ShoeDetail.as_view(), name='shoes_detail'),
    path('shoes/create/', views.ShoeCreate.as_view(), name='shoes_create'),
    path('shoes/<int:pk>/update/', views.ShoeUpdate.as_view(), name='shoes_update'),
    path('shoes/<int:pk>/delete/', views.ShoeDelete.as_view(), name='shoes_delete'),
    path('players/<int:player_id>/add_photo/', views.add_photo, name='add_photo'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from distutils.command.upload import upload
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

OPTIONS = (
    ('A', 'Away'),
    ('H', 'Home'),
    ('P', 'Playoffs')
)

# Create your models here.

class Shoes(models.Model):
  name = models.CharField(max_length=50)
  size = models.FloatField(null = True)
 
  def __str__(self):
    return f'{self.name} {self.size}'

  def get_absolute_url(self):
    return reverse('shoes_detail', kwargs={'shoe_id': self.id})

class Player(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    height = models.CharField(max_length= 50, null=True)
    weight = models.CharField(max_length=50, null=True)
    college = models.CharField(max_length=50, null=True)
    ppg = models.FloatField(null= True)
    apg = models.FloatField(null= True)
    rpg = models.FloatField(null= True) 
    spg = models.FloatField(null= True)
    per = models.FloatField(null = True)
    shoes = models.ManyToManyField(Shoes)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    
    def no_more_games_today(self):
      return self.games_set.filter(date=date.today()).count() >= len(OPTIONS)

    def __str__(self):
      return self.name

    def get_absolute_url(self):
      return reverse('detail', kwargs={'player_id': self.id})

class Games(models.Model):
  date = models.DateField()
  game = models.CharField(
      max_length=1,
      choices=OPTIONS,
      default=OPTIONS[0][0]
  )

  player = models.ForeignKey(Player, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_game_display()} on {self.date}"

  
  class Meta:
    ordering = ['-date']

class Photo(models.Model):
  url = models.CharField(max_length=200)
  player = models.ForeignKey(Player, on_delete=models.CASCADE)


  def __str__(self):
    return f"Photo for player_id: {self.player_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Games

class GamesForm(ModelForm):
  class Meta:
    model = Games
    fields = ['date', 'game']

main_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from main_app.forms import GamesForm
from .models import Player, Shoes, Photo
from main_app.forms import GamesForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.http import Http404

import uuid
import boto3

S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'bball-proj'


def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

@login_required
def players_index(request):
  players = Player.objects.filter(user=request.user)
  return render(request, 'players/index.html', { 'players': players })

@login_required
def players_detail(request, player_id):
  player = Player.objects.get(id=player_id)
  shoes_player_doesnt_have = Shoes.objects.exclude(id__in = player.shoes.all().values_list('id'))
  games_form = GamesForm()
  return render(request, 'players/detail.html',{
    'player': player, 'games_form': games_form,
    'shoes': shoes_player_doesnt_have
    })


@login_required
def add_game(request, player_id):
  form = GamesForm(request.POST)
  if form.is_valid():
    new_game = form.save(commit=False)
    new_game.player_id = player_id
    new_game.save()
  return redirect('detail', player_id=player_id)


@login_required
def assoc_shoe(request, player_id, shoe_id):
  Player.objects.get(id=player_id).shoes.add(shoe_id)
  return redirect('detail', player_id=player_id)

@login_required
def assoc_shoe_delete(request, player_id, shoe_id):
  Player.objects.get(id=player_id).shoes.remove(shoe_id)
  return redirect('detail', player_id=player_id)

@login_required
def add_photo(request, player_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
      s3 = boto3.client('s3')
      key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
      try:
        s3.upload_fileobj(photo_file, BUCKET, key)
        url = f"{S3_BASE_URL}{BUCKET}/{key}"
        photo = Photo(url=url, player_id=player_id)
        photo.save()
        print(photo)
      except:
        print('An error occured uploading file to s3')
    return redirect('detail', player_id=player_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
  else:
    error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

class PlayerCreate(LoginRequiredMixin, CreateView):
  model = Player
  fields = ['name', 'age', 'height', 'weight', 'college', 'ppg', 'apg', 'rpg', 'spg', 'per'] 
  success_url = '/players/'

  def form_valid(self, form):
    form.instance.user = self.request.user  
    return super().form_valid(form)



class PlayerUpdate(LoginRequiredMixin, UpdateView):
  model = Player
  fields = ['name', 'age', 'height', 'weight', 'college', 'ppg', 'apg', 'rpg', 'spg', 'per'] 
  success_url = '/players/'
  

class PlayerDelete(LoginRequiredMixin, DeleteView):
  model = Player
  fields = '__all__'
  success_url = '/players/'

class ShoeList(LoginRequiredMixin, ListView):
  model = Shoes
  template_name = 'shoes/index.html'


class ShoeDetail(LoginRequiredMixin, DetailView):
  model = Shoes
  template_name = 'shoes/detail.html'


class ShoeCreate(LoginRequiredMixin, CreateView):
    model = Shoes
    fields = ['name', 'size']
    success_url = '/shoes/'

    def form_valid(self, form):
      form.instance.user = self.request.user  
      return super().form_valid(form)


class ShoeUpdate(LoginRequiredMixin, UpdateView):
  model = Shoes
  fields = ['name', 'size']
  success_url = '/shoes/'

class ShoeDelete(LoginRequiredMixin, DeleteView):
  model = Shoes
  fields = '__all__'
  success_url = '/shoes/'




  

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<h1 id = "ourStory"> Our Story... <i class="em em-book" aria-role="presentation" aria-label="OPEN BOOK"></i> <div class="leftBallHead"> <i class='fas fa-basketball-ball'></i> </div></h1>
<div class="aboutParagraph">
  <p id="aboutParagraph"> Basketballs_My_Player has allowed <br> avid and authenticated basketball fans <br> the ability to create, read, update, and delete <br> both shoes and players! Users are also able <br> to add games for each player created <br> (a one to many relationship between <br> players and games). AWS is included as well to allow users the ability to insert pictures for their players! </p>
</div>



{% endblock %} 

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link href="https://emoji-css.afeld.me/emoji.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">            
    <title> Bball Draft </title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="left brand-logo">  <div class = "leftBball"> <i class='fas fa-basketball-ball'></i> </div> BASKETBALLS_MY_PLAYER <div class= "rightBball"> <i class='fas fa-basketball-ball'></i> <i class='fas fa-basketball-ball'></i> </div> </a> 
            </li> 
          </ul>
          <ul class="right">
            <li class= "navItemStyling"><a href="{% url 'about' %}" id = "aboutNav">About</a></li>
            {% if user.is_authenticated %}
            <li><a class= "navItemStyling" href="{% url 'shoes_create' %}">Add Shoes</a></li>
            <li><a class= "navItemStyling" href="{% url 'shoes_index' %}">View Shoes</a></li>
            <li><a class= "navItemStyling" href="{% url 'players_create' %}">Add Players</a></li>
            <li><a class= "navItemStyling" href="{% url 'index' %}">View Players</a></li>
            <li><a class= "navItemStyling" href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a class= "navItemStyling" href="{% url 'login' %}">Log In</a></li>
            <li><a class= "navItemStyling" href="{% url 'signup' %}">Sign Up</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        <div class= "rightBball">
        <i class='fas fa-basketball-ball'></i>
        <i class='fas fa-basketball-ball'></i>
        <i class='fas fa-basketball-ball'></i>
        </div>
        All Rights Reserved, © 2022 BASKETBALLS_MY_PLAYER
      </div>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}

<h1 id = "attentionHead"> <div class="leftBallHead"><i class='fas fa-basketball-ball'></i> </div> ATTENTION ALL BASKETBALL FANS <div class="rightBballHead"><i class='fas fa-basketball-ball'></i> </div> <h1>
<h1 id = "signupIf"> Sign-Up if... You Like Basketball <div class="exclamationMark1">&#33;</div> 
<div class="exclamationMark2"><span>&#33;</span> 
</div> 
<div class="exclamationMark3"><span>&#33;</span>
</div> 
</h1>


{% endblock %} 

main_app/templates/main_app/player_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Player</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' player.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/player_form.html
{% extends 'base.html' %} 
{% block content %}
{% if object %}
<h1 class="editPlayerHeader"> <i class="em em-man-bouncing-ball" aria-role="presentation" aria-label=""></i> Edit  {{object.name}} <i class="em em-woman-bouncing-ball" aria-role="presentation" aria-label=""></i></h1>
{% else %}
<div class="addPlayerContainer">
  <h1 class = "addPlayerHeader"> <i class="em em-man-bouncing-ball" aria-role="presentation" aria-label=""></i> Add a Player <i class="em em-woman-bouncing-ball" aria-role="presentation" aria-label=""></i> </h1>
{% endif %}
<ul class="playerKey">
  <li class = "playerKey">| PPG - points per game |</li>
  <li class = "playerKey">| APG - Assists per game |</li>
  <li class = "playerKey">| RPG - Rebounds per game |</li>
  <li class = "playerKey">| SPG - Steals per game |</li>
  <li class = "playerKey">| PER - Player efficiency rating |</li>
</ul>



<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="SUBMIT PLAYER" class="btn" />
</form>
<br>
<br>
<br>
<br>

</div>



{% endblock %}

main_app/templates/main_app/shoe_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Update {{ object.name }}</h1>
{% else %}
<h1> Add Shoe </h1>
{% endif %}

<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input
    class="btn blue"
    type="submit"
    value="{% if object %} Update Shoes {% else %} Add Shoes {% endif %}"
  />
</form>

{% endblock %}

main_app/templates/main_app/shoes_confirm_delete.html
{% extends 'base.html' %} {% block content %}

<h1>Delete Shoe</h1>

<h4>
  Are you sure you want to delete
  <span>{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' shoes.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/shoes_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1 class="editShoeHead"> <i class="em em-athletic_shoe" aria-role="presentation" aria-label="ATHLETIC SHOE"></i> Edit {{ object.name }} <i class="em em-athletic_shoe" aria-role="presentation" aria-label="ATHLETIC SHOE"></i> </h1>
{% else %}
<h1 class = "addShoeHead"><i class="em em-athletic_shoe" aria-role="presentation" aria-label="ATHLETIC SHOE"></i></i> Add a Shoe <i class="em em-athletic_shoe" aria-role="presentation" aria-label="ATHLETIC SHOE"></i></i></h1>
{% endif %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <br>
  <input
    class="updateShoeBtn"
    type="submit"
    value="{% if object %} SUBMIT SHOE {% else %} SUBMIT SHOE {% endif %}"
  />
</form>

{% endblock %}

main_app/templates/players/detail.html
{% extends 'base.html' %} {% block content %}

<h1 class = "myPlayerHeader"> <i class="em em-man-bouncing-ball" aria-role="presentation" aria-label=""></i>  My Player Details <i class="em em-woman-bouncing-ball" aria-role="presentation" aria-label=""></i></h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-titlePlayer">{{ player.name }}:</span>
        <ul class="playerKey">
          <li class = "playerKey">| PPG - points per game |</li>
          <li class = "playerKey">| APG - Assists per game |</li>
          <li class = "playerKey">| RPG - Rebounds per game |</li>
          <li class = "playerKey">| SPG - Steals per game |</li>
          <li class = "playerKey">| PER - Player efficiency rating |</li>
        </ul>
          {% if player.age > 0 %}
          <p>Age: {{ player.age }}</p>
          <p>Height: {{ player.height }}</p>
          <p>Weight: {{ player.weight }}</p>
          <p>College: {{ player.college }}</p>
          <p>PPG: {{ player.ppg }}</p>
          <p>APG: {{ player.apg }}</p>
          <p>RPG: {{ player.rpg }}</p>
          <p>SPG: {{ player.spg }}</p>
          <p>PER: {{ player.per }}</p>
        {% else %}
        <p>Age: n/a</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'players_update' player.id %}">Edit</a>
        <a href="{% url 'players_delete' player.id %}">Delete</a>
      </div>
    </div>

  <form action="{% url 'add_game' player.id %}" method="post">
      {% csrf_token %} {{ games_form.as_p }}
      <input type="submit" class="btn" value="Add Game" />
  </form>
    <br />
    {% if player.no_more_games_today %}
    <div class="card-panel teal-text center-align">
      {{player.name }} has played all games today
    </div>
    {% else %}
    <div class="card-panel red-text center-align">
      {{player.name}}  might have more games coming soon
    </div>
    {% endif %}
    {% for photo in player.photo_set.all %}
      <img class="responsive-img card-panel" src="{{ photo.url }}" alt="{{ player.name }}">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded (Upload a Picture of your Player)</div>
    {% endfor %}
    <form
      action="{% url 'add_photo' player.id %}"
      class="card-panel"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br /> 
      <br /> 
      <input type="submit" class="btn" value="Upload Photo">
    </form>
  </div>
    <div class="col s6">
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Game</th>
        </tr>
      </thead>
      <tbody>
        {% for game in player.games_set.all %}
        <tr>
          <td>{{game.date}}</td>
          <td>{{game.get_game_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
</div>
<hr />
<div class = "row">
  <div class="col s6">
    <h3> <i class="em em-athletic_shoe" aria-role="presentation" aria-label="ATHLETIC SHOE"></i> {{ player.name }}'s Shoes</h3>
    {% if player.shoes.count %} {% for shoe in player.shoes.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
        <span> Shoe Name: {{ shoe.name }}</span> <br>
        <span> Shoe Size: {{ shoe.size }}</span>

    </div>
    <div class="card-action">
      <form action="{% url 'assoc_shoe_delete' player.id shoe.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn">Remove</button>
      </form>
    </div>
  </div>
  {% endfor %} {% else %}
  <h5> No Shoes :/ Go add some! </h5>
  {% endif %}
</div>
<div class="col s6">
  <h3><i class="em em-athletic_shoe" aria-role="presentation" aria-label="ATHLETIC SHOE"></i> Available Shoes</h3>
  {% if shoes.count %} {% for shoe in shoes.all %}
  <div class="card">
    <div class="card-content">
      <span class="card-title">
        <span> Shoe Name: {{ shoe.name }}</span> <br>
        <span> Shoe Size: {{ shoe.size }}</span>
    </div>
    <div class="card-action">
      <form action="{% url 'assoc_shoe' player.id shoe.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn">Add</button>
      </form>
    </div>
  </div>
  {% endfor %} {% else %}
  <h5>{{player.name}} Already Has All shoes Available</h5>
  {% endif %}
</div>

    <script>
      var dateEl = document.getElementById('id_date');
      M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
      });

      var selectEl = document.getElementById('id_game');
      M.FormSelect.init(selectEl);
    </script>
  {% endblock %}
  </div>

main_app/templates/players/index.html
{% extends 'base.html' %} {% block content %}
<h1 id = "bball-list"> <i class="em em-man-bouncing-ball" aria-role="presentation" aria-label=""></i> Basketball Player List <i class="em em-woman-bouncing-ball" aria-role="presentation" aria-label=""></i></h1>

{% for player in players %}
<div class="card">
  <a href ="{% url 'detail' player.id %}">
    <div class="card-content">

      <span class="card-titlePlayer">{{ player.name }}:</span>
      {% if player.age > 0 %}
      <p>Age: {{ player.age }}</p>
      <p>Height: {{ player.height }}</p>
      <p>Weight: {{ player.weight }}</p>
      <p>College: {{ player.college }}</p>
      <p>PPG: {{ player.ppg }}</p>
      <p>APG: {{ player.apg }}</p>
      <p>RPG: {{ player.rpg }}</p>
      <p>SPG: {{ player.spg }}</p>
      <p>PER: {{ player.per }}</p>
     
      <button class="detailsBtn"> View Details </button>
      {% else %}
      <p>Age: n/a</p>
      {% endif %}
    </div>
  </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/shoes/detail.html
{% extends 'base.html' %} {% block content %}

<h1 class = "shoeDetailsHead"> <i class="em em-athletic_shoe" aria-role="presentation" aria-label="ATHLETIC SHOE"></i></i>
  Shoe Details <i class="em em-athletic_shoe" aria-role="presentation" aria-label="ATHLETIC SHOE"></i></i> </h1>

<div class="card">
  <a href="{% url 'shoes_detail' shoes.id %}">
    <div class="card-content">
      <span class="card-title">
        <span>SIZE: {{ shoes.size }}</span> <br>
        SHOE NAME: {{shoes.name}}</span>
    </div>
    <div class="card-action">
      <a href="{% url 'shoes_update' shoes.id %}">Edit</a>
      <a href="{% url 'shoes_delete' shoes.id %}">Delete</a>
    </div> 
  </a>
</div>

{% endblock %}

main_app/templates/shoes/index.html
{% extends 'base.html' %} {% block content %}

<h1 class = "shoeHeader" > <i class="em em-athletic_shoe" aria-role="presentation" aria-label="ATHLETIC SHOE"></i> My Shoe Collection <i class="em em-athletic_shoe" aria-role="presentation" aria-label="ATHLETIC SHOE"></i></h1>

{% for shoe in object_list %}
<div class="card">
  <a href="{% url 'shoes_detail' shoe.id %}">
    <div class="card-content">
      <span class="card-title">
        <span class="{{shoe.size}}-text">Shoe Size: {{shoe.size}}</span> <br> Shoe Name: {{shoe.name}}</span>
        <button class ="detailsBtn"> View Details </button>
    </div>
  </a>
</div>

{% endfor %} {% endblock%}